name: Rubocop

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 21 * * 6"

jobs:
  rubocop:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.1", "3.2", "3.3", "jruby-9.4"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          rubygems: latest
          bundler: latest
          bundler-cache: true
      - uses: r7kamura/rubocop-problem-matchers-action@v1.2.2
      - run: bin/rubocop --parallel
